### ISSUE TITLE
LLD?

### ISSUE THREAD

**Issue by ghost** [tpoechtrager/wclang#8]
MinGW's linker is painfully slow. Do you know is it possible to compile and use LLD for windows builds as well?

**Comment by martell** [comment]
@tpoechtrager There is now 2 people :)

https://github.com/llvm-mirror/lld/pull/3
I have it linking correctly in ld emulation mode for mingw-w64-x86_64 and I am merging upstream ;)

**Comment by tpoechtrager** [comment]
@martell:

Finally MinGW support for LLD :smile:. Keep up the good work!

Now if someone would also take care of clang's MinGW driver...

**Comment by martell** [comment]
@tpoechtrager I've done that as well.
The mingw-driver is part of the clang package in msys2

**Comment by martell** [comment]
@tpoechtrager I would like to ask for help with something though and based on the project you have here you would be perfectly suited to helping me with this issue.

When calling dlltool it uses binutils AS to turns defs into .a libs in mingw-w64
I want to replace this with clang.
This is very important for 2 reasons

1. arm because we obviously don't have gcc or binutils for armv7 win32
2. we should be able to build mingw-w64 without gcc or binutils at all :)

**Comment by tpoechtrager** [comment]
I have taken a quick look at it, first of all, good job.

However, I came across a few things that could be tweaked:

* You should really get rid of the hardcoded `-lpthread`, `libwinpthread.dll` is a really annoying dependency.
* Looking for headers in `/usr/<triple>/` won't work on everywhere, especially not on Linux where every distribution is doing its own packaging madness.

I could help out with the later one once I have enough time for it. I would be really interested in moving wclang's search logic directly into the clang driver.

---

> Must work on building mingw-w64 completely with clang and without gcc soon :)

I would put that on a low priority list, `libc++` would be of way more interest. Nobody really cares if a few crt object files are built by gcc instead of clang (at least not for now :smile:).

---

> When calling dlltool it uses binutils AS to turns defs into .a libs in mingw-w64
I want to replace this with clang but --as=clang doesn't work as well as we want :(
This is very important for 2 reasons

Sorry, I have no idea about Windows + ARM...

> we should be able to build mingw-w64 without gcc or binutils at all :)

Binutils builds successfully with clang.

**Comment by martell** [comment]
> However, I came across a few things that could be tweaked:
>    You should really get rid of the hardcoded -lpthread, libwinpthread.dll is a really annoying dependency.

This was mostly taken because it was a default link library for gcc so it was made to act the same.
I do see your point though. There should be an option to add it instead.

>    Looking for headers in /usr/<triple>/ won't work on everywhere, especially not on Linux where every distribution is doing its own packaging madness.
>I could help out with the later one once I have enough time for it. I would be really interested in moving wclang's search logic directly into the clang driver.

Yes the focus here has been mostly for a windows host and not linux
Any improvements here would be very welcome

> I would put that on a low priority list, libc++ would be of way more interest. Nobody really cares if a few crt object files are built by gcc instead of clang (at least not for now :smile:).

> Edit: Never mind, I see you already have a libc++ package...

Well my thinking here was on using compiler-rt instead of libgcc 
The libc++ package isn't fully ready yet :)

> Sorry, I have no idea about Windows + ARM...

Well this isn't so much about windows on ARM its more about being able to use clang instead of AS.
I'm told that we should be able to do this, of course I would like to do this on i686 first.
It should be possible because clang can emit assembly just like binutils and gcc

**Comment by tpoechtrager** [comment]
> This was mostly taken because it was a default link library for gcc so it was made to act the same.

You are right, my MinGW installation is doing the same (probably because of `--enabled-threads=posix`), quite awful.

> Yes the focus here has been mostly for a windows host and not linux
> Any improvements here would be very welcome

Sure thing! I will look at it soon.

> Well my thinking here was on using compiler-rt instead of libgcc 
> The libc++ package isn't fully ready yet :)

compiler-rt would be really interesting too, especially because of all the sanitizer stuff.

> Well this isn't so much about windows on ARM its more about being able to use clang instead of AS.
> I'm told that we should be able to do this, of course I would like to do this on i686 first.
> It should be possible because clang can emit assembly just like binutils and gcc

Have you tried `--as llvm-as` instead of `--as clang`?

**Comment by procedural** [comment]
@tpoechtrager jesus christ, Martell, I've just compiled an openFrameworks application with Clang on Windows! I'll write a post about it on my blog

**Comment by martell** [comment]
sounds cool :)

In the last 2 weeks I have successfully built a mingw-w64 compiler with clang only.
We can throw gcc in the bin now :D

I had many of the patches broken down and merged

http://reviews.llvm.org/D11087
http://reviews.llvm.org/D11088
http://reviews.llvm.org/D11085
http://reviews.llvm.org/D11071
http://reviews.llvm.org/D11075
http://reviews.llvm.org/D11237

As well as many patches went into mingw-w64 to support it being built with clang :)

If http://reviews.llvm.org/D11237 makes the 3.7 release I will do a package on it

Looking forward to your blog post :)

**Comment by tpoechtrager** [comment]
@martell: Very well done! Clang+MinGW feels a lot better now.

Whenever you have a little bit of time, it would be great if you could have a look at:

https://llvm.org/bugs/show_bug.cgi?id=24182

Thanks!

**Comment by martell** [comment]
@tpoechtrager: they have opted to disable that option by default because mingw.org compilers don't have it. It's very easy to change but they won't merge that change.
See the comments in http://reviews.llvm.org/D11087

It's a mingw-w64 issue, they should support c11 threads and we should not have to link with -pthread by default

**Comment by tpoechtrager** [comment]
@martell: Having c11 thread support won't fix the issue for libstdc++, they are using pthreads. I don't want to hack the clang driver, I would like to have clang to link pthread by default if the lib is present in `<sysroot>/lib`, or at least when `-stdlib=libstdc++` is used.

**Comment by tpoechtrager** [comment]
@martell: btw, the darwin driver is doing a similar approach with libcompiler_rt, the library only gets linked when it's installed.

**Comment by martell** [comment]
@tpoechtrager: I'll have a look at this.
I think a better way though would be to find out if we are using mingw.org or mingw-w64 toolchains and then do it based on that

**Comment by tpoechtrager** [comment]
@martell: MinGW-w64 can also be built without winpthreads, it's gcc's `--enable-threads=posix` configure option.

**Comment by martell** [comment]
Ahh yea that is very true actually.
I'll have a look at the darwin code and see if I can come up with something
